version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ${POSTGRES_HOST:-database}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - home-library-network
    restart: unless-stopped

  app:
    build: .
    container_name: app
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST:-database}:5432/${POSTGRES_DB}?schema=public
      PORT: ${PORT:-4000}
    ports:
      - "${PORT:-4000}:${PORT:-4000}"
    depends_on:
      - postgres
    networks:
      - home-library-network
    restart: always
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma

volumes:
  postgres_data:
  postgres_logs:

networks:
  home-library-network:
    driver: bridge